// <auto-generated />
using System;
using EventRep.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EventRep.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EventRepDbContext))]
    partial class EventRepDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EventRep.Infrastructure.Persistence.Models.EventFeedbackOrm", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<Guid>("ExecutorId")
                        .HasColumnType("uuid")
                        .HasColumnName("executor_id");

                    b.HasKey("Id");

                    b.HasIndex("ExecutorId")
                        .HasDatabaseName("ix_event_feedbacks_executor_id");

                    b.HasIndex("EventId", "ExecutorId")
                        .IsUnique()
                        .HasDatabaseName("ux_event_feedbacks_event_executor");

                    b.ToTable("event_feedbacks", (string)null);
                });

            modelBuilder.Entity("EventRep.Infrastructure.Persistence.Models.EventOrm", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<Guid?>("ExecutorId")
                        .HasColumnType("uuid")
                        .HasColumnName("executor_id");

                    b.Property<DateTime>("FullDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("full_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<TimeSpan>("TimeEnd")
                        .HasColumnType("time without time zone")
                        .HasColumnName("time_end");

                    b.Property<TimeSpan>("TimeStart")
                        .HasColumnType("time without time zone")
                        .HasColumnName("time_start");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_events_customer_id");

                    b.HasIndex("ExecutorId")
                        .HasDatabaseName("ix_events_executor_id");

                    b.HasIndex("Status", "FullDate")
                        .HasDatabaseName("ix_events_status_full_date");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("EventRep.Infrastructure.Persistence.Models.PortfolioElementOrm", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uuid")
                        .HasColumnName("portfolio_id");

                    b.Property<string>("S3File")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("s3_file");

                    b.Property<string>("S3Key")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("s3_key");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioId")
                        .HasDatabaseName("ix_portfolio_elements_portfolio_id");

                    b.HasIndex("S3Key")
                        .IsUnique()
                        .HasDatabaseName("ux_portfolio_elements_s3_key");

                    b.ToTable("portfolio_elements", (string)null);
                });

            modelBuilder.Entity("EventRep.Infrastructure.Persistence.Models.PortfolioOrm", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CountWorks")
                        .HasColumnType("integer")
                        .HasColumnName("count_works");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_portfolios_user_id");

                    b.ToTable("portfolios", null, t =>
                        {
                            t.HasCheckConstraint("ck_portfolios_count_works", "count_works >= 0");
                        });
                });

            modelBuilder.Entity("EventRep.Infrastructure.Persistence.Models.ResumeOrm", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<Guid?>("PortfolioEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("portfolio_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioEntityId")
                        .IsUnique()
                        .HasDatabaseName("ux_resumes_portfolio_id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_resumes_user_id");

                    b.ToTable("resumes", (string)null);
                });

            modelBuilder.Entity("EventRep.Infrastructure.Persistence.Models.UserOrm", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("Age")
                        .HasColumnType("smallint")
                        .HasColumnName("age");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("gender");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("phone_number");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_users_created_at");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_users_phone_number");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_age", "age BETWEEN 0 AND 150");
                        });
                });

            modelBuilder.Entity("EventRep.Infrastructure.Persistence.Models.EventFeedbackOrm", b =>
                {
                    b.HasOne("EventRep.Infrastructure.Persistence.Models.EventOrm", "Event")
                        .WithMany("Feedbacks")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventRep.Infrastructure.Persistence.Models.UserOrm", "Executor")
                        .WithMany("EventFeedbacks")
                        .HasForeignKey("ExecutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Executor");
                });

            modelBuilder.Entity("EventRep.Infrastructure.Persistence.Models.EventOrm", b =>
                {
                    b.HasOne("EventRep.Infrastructure.Persistence.Models.UserOrm", "Customer")
                        .WithMany("CustomerEvents")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EventRep.Infrastructure.Persistence.Models.UserOrm", "Executor")
                        .WithMany("ExecutedEvents")
                        .HasForeignKey("ExecutorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Customer");

                    b.Navigation("Executor");
                });

            modelBuilder.Entity("EventRep.Infrastructure.Persistence.Models.PortfolioElementOrm", b =>
                {
                    b.HasOne("EventRep.Infrastructure.Persistence.Models.PortfolioOrm", "Portfolio")
                        .WithMany("Elements")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("EventRep.Infrastructure.Persistence.Models.PortfolioOrm", b =>
                {
                    b.HasOne("EventRep.Infrastructure.Persistence.Models.UserOrm", "User")
                        .WithOne("Portfolio")
                        .HasForeignKey("EventRep.Infrastructure.Persistence.Models.PortfolioOrm", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EventRep.Infrastructure.Persistence.Models.ResumeOrm", b =>
                {
                    b.HasOne("EventRep.Infrastructure.Persistence.Models.PortfolioOrm", "Portfolio")
                        .WithOne("Resume")
                        .HasForeignKey("EventRep.Infrastructure.Persistence.Models.ResumeOrm", "PortfolioEntityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EventRep.Infrastructure.Persistence.Models.UserOrm", "User")
                        .WithOne("Resume")
                        .HasForeignKey("EventRep.Infrastructure.Persistence.Models.ResumeOrm", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Portfolio");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EventRep.Infrastructure.Persistence.Models.EventOrm", b =>
                {
                    b.Navigation("Feedbacks");
                });

            modelBuilder.Entity("EventRep.Infrastructure.Persistence.Models.PortfolioOrm", b =>
                {
                    b.Navigation("Elements");

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("EventRep.Infrastructure.Persistence.Models.UserOrm", b =>
                {
                    b.Navigation("CustomerEvents");

                    b.Navigation("EventFeedbacks");

                    b.Navigation("ExecutedEvents");

                    b.Navigation("Portfolio");

                    b.Navigation("Resume");
                });
#pragma warning restore 612, 618
        }
    }
}
