import type { EventItem } from './types'

export const events: EventItem[] = [
  {
    id: 1,
    title: 'Камерная свадьба в старинной усадьбе',
    category: 'Свадьбы',
    date: '18 октября 2026',
    day: '18',
    month: 'ОКТ',
    city: 'Москва',
    place: 'Усадьба Муравьёвых-Апостолов',
    price: 65000,
    role: 'Фотограф',
    tags: ['Репортаж', '6–8 часов', 'Портфолио'],
    author: 'Алина К.',
    avatar: 'АК',
    responses: 7,
    urgent: true,
    color: '#ff785a',
  },
  {
    id: 2,
    title: 'День рождения в стиле «Великий Гэтсби»',
    category: 'Дни рождения',
    date: '24 октября 2026',
    day: '24',
    month: 'ОКТ',
    city: 'Санкт-Петербург',
    place: 'Особняк Мясникова',
    price: 45000,
    role: 'Ведущий',
    tags: ['25 гостей', 'Свой реквизит', '5 часов'],
    author: 'Максим О.',
    avatar: 'МО',
    responses: 12,
    color: '#83a2ff',
  },
  {
    id: 3,
    title: 'Летний корпоратив продуктовой команды',
    category: 'Корпоративы',
    date: '2 ноября 2026',
    day: '02',
    month: 'НОЯ',
    city: 'Казань',
    place: 'Загородный клуб «Свияга»',
    price: 90000,
    role: 'Кавер-группа',
    tags: ['80 гостей', 'Живой звук', '2 сета'],
    author: 'Кира, HR lead',
    avatar: 'КЛ',
    responses: 4,
    color: '#c7d95b',
  },
  {
    id: 4,
    title: 'Акустический концерт на крыше',
    category: 'Концерты',
    date: '7 ноября 2026',
    day: '07',
    month: 'НОЯ',
    city: 'Екатеринбург',
    place: 'Крыша «Дом печати»',
    price: 35000,
    role: 'Видеограф',
    tags: ['2 камеры', 'Цветокор', 'Тизер'],
    author: 'Миша Р.',
    avatar: 'МР',
    responses: 9,
    color: '#f6be62',
  },
  {
    id: 5,
    title: 'Ужин по случаю годовщины родителей',
    category: 'Другое',
    date: '15 ноября 2026',
    day: '15',
    month: 'НОЯ',
    city: 'Москва',
    place: 'Ресторан «Дом культур»',
    price: 28000,
    role: 'Декоратор',
    tags: ['10 гостей', 'Цветы', 'Монтаж'],
    author: 'Антон В.',
    avatar: 'АВ',
    responses: 3,
    color: '#de8bb7',
  },
  {
    id: 6,
    title: 'Свадебная вечеринка без официоза',
    category: 'Свадьбы',
    date: '21 ноября 2026',
    day: '21',
    month: 'НОЯ',
    city: 'Нижний Новгород',
    place: 'Терраса «Маяк»',
    price: 50000,
    role: 'DJ',
    tags: ['40 гостей', 'Оборудование', '6 часов'],
    author: 'Лера и Дима',
    avatar: 'ЛД',
    responses: 5,
    color: '#77cbb9',
  },
]

export const categories = ['Все события', 'Свадьбы', 'Дни рождения', 'Корпоративы', 'Концерты', 'Другое'] as const
