-- Схема Событие.рф. Запустите файл в Supabase SQL Editor.
create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default 'Гость',
  avatar text not null default 'ГС',
  role text,
  city text,
  bio text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  owner_id uuid references auth.users(id) on delete set null,
  title text not null check (char_length(title) between 3 and 140),
  category text not null check (category in ('Свадьбы', 'Дни рождения', 'Корпоративы', 'Концерты', 'Другое')),
  role text not null,
  description text,
  event_date date not null,
  start_time time,
  duration text,
  city text not null,
  place text not null default 'Место уточняется',
  price integer not null check (price >= 0),
  tags text[] not null default '{}',
  organizer_name text not null default 'Организатор',
  organizer_avatar text not null default 'ОР',
  accent_color text not null default '#ff785a',
  is_urgent boolean not null default false,
  response_count integer not null default 0 check (response_count >= 0),
  status text not null default 'open' check (status in ('open', 'closed', 'draft')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (title, event_date)
);

create table if not exists public.responses (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.events(id) on delete cascade,
  responder_id uuid not null references auth.users(id) on delete cascade,
  responder_name text not null,
  responder_role text not null,
  message text not null check (char_length(message) between 10 and 2000),
  proposed_price integer not null check (proposed_price >= 0),
  delivery_term text,
  status text not null default 'pending' check (status in ('pending', 'accepted', 'rejected')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (event_id, responder_id)
);

create table if not exists public.favorites (
  user_id uuid not null references auth.users(id) on delete cascade,
  event_id bigint not null references public.events(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, event_id)
);

create index if not exists events_owner_id_idx on public.events(owner_id);
create index if not exists events_status_date_idx on public.events(status, event_date);
create index if not exists responses_event_id_idx on public.responses(event_id);
create index if not exists responses_responder_id_idx on public.responses(responder_id);
create index if not exists favorites_user_id_idx on public.favorites(user_id);

create or replace function public.set_updated_at()
returns trigger language plpgsql set search_path = '' as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.sync_event_response_count()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  if tg_op = 'INSERT' then
    update public.events set response_count = response_count + 1 where id = new.event_id;
    return new;
  elsif tg_op = 'DELETE' then
    update public.events set response_count = greatest(response_count - 1, 0) where id = old.event_id;
    return old;
  end if;
  return null;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at before update on public.profiles
for each row execute function public.set_updated_at();
drop trigger if exists events_set_updated_at on public.events;
create trigger events_set_updated_at before update on public.events
for each row execute function public.set_updated_at();
drop trigger if exists responses_set_updated_at on public.responses;
create trigger responses_set_updated_at before update on public.responses
for each row execute function public.set_updated_at();
drop trigger if exists responses_sync_count on public.responses;
create trigger responses_sync_count after insert or delete on public.responses
for each row execute function public.sync_event_response_count();

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  insert into public.profiles (id, display_name)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'display_name', 'Гость'))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute function public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.events enable row level security;
alter table public.responses enable row level security;
alter table public.favorites enable row level security;

revoke all on public.profiles, public.events, public.responses, public.favorites from anon, authenticated;
grant select, insert, update, delete on public.profiles, public.events, public.responses, public.favorites to authenticated;
grant select on public.events to anon;
grant usage, select on all sequences in schema public to authenticated;

create policy "Public can read open events" on public.events
for select to anon, authenticated
using (status = 'open' or owner_id = (select auth.uid()));

create policy "Users create own events" on public.events
for insert to authenticated
with check (owner_id = (select auth.uid()));

create policy "Owners update events" on public.events
for update to authenticated
using (owner_id = (select auth.uid()))
with check (owner_id = (select auth.uid()));

create policy "Owners delete events" on public.events
for delete to authenticated
using (owner_id = (select auth.uid()));

create policy "Profiles are publicly readable" on public.profiles
for select to authenticated using (true);
create policy "Users insert own profile" on public.profiles
for insert to authenticated with check (id = (select auth.uid()));
create policy "Users update own profile" on public.profiles
for update to authenticated using (id = (select auth.uid())) with check (id = (select auth.uid()));
create policy "Users delete own profile" on public.profiles
for delete to authenticated using (id = (select auth.uid()));

create policy "Participants read responses" on public.responses
for select to authenticated
using (
  responder_id = (select auth.uid()) or exists (
    select 1 from public.events e where e.id = responses.event_id and e.owner_id = (select auth.uid())
  )
);
create policy "Users create own responses" on public.responses
for insert to authenticated
with check (
  responder_id = (select auth.uid()) and exists (
    select 1 from public.events e where e.id = responses.event_id and e.status = 'open'
  )
);
create policy "Responders update own responses" on public.responses
for update to authenticated
using (responder_id = (select auth.uid())) with check (responder_id = (select auth.uid()));
create policy "Responders delete own responses" on public.responses
for delete to authenticated using (responder_id = (select auth.uid()));

create policy "Users read own favorites" on public.favorites
for select to authenticated using (user_id = (select auth.uid()));
create policy "Users add own favorites" on public.favorites
for insert to authenticated with check (user_id = (select auth.uid()));
create policy "Users delete own favorites" on public.favorites
for delete to authenticated using (user_id = (select auth.uid()));

-- Демо-карточки. owner_id = null означает системную публикацию.
insert into public.events
  (title, category, role, description, event_date, start_time, duration, city, place, price, tags, organizer_name, organizer_avatar, accent_color, is_urgent)
values
  ('Камерная свадьба в старинной усадьбе', 'Свадьбы', 'Фотограф', 'Ищем фотографа, который поймает атмосферу камерного праздника.', '2026-10-18', '16:00', '6–8 часов', 'Москва', 'Усадьба Муравьёвых-Апостолов', 65000, array['Репортаж','6–8 часов','Портфолио'], 'Алина К.', 'АК', '#ff785a', true),
  ('День рождения в стиле «Великий Гэтсби»', 'Дни рождения', 'Ведущий', 'Нужен тактичный ведущий с собственной программой.', '2026-10-24', '18:00', '5 часов', 'Санкт-Петербург', 'Особняк Мясникова', 45000, array['25 гостей','Свой реквизит','5 часов'], 'Максим О.', 'МО', '#83a2ff', false),
  ('Летний корпоратив продуктовой команды', 'Корпоративы', 'Кавер-группа', 'Живой сет для продуктовой команды на загородной площадке.', '2026-11-02', '17:00', '2 сета', 'Казань', 'Загородный клуб «Свияга»', 90000, array['80 гостей','Живой звук','2 сета'], 'Кира, HR lead', 'КЛ', '#c7d95b', false),
  ('Акустический концерт на крыше', 'Концерты', 'Видеограф', 'Съёмка концерта и динамичный тизер для социальных сетей.', '2026-11-07', '19:00', '4 часа', 'Екатеринбург', 'Крыша «Дом печати»', 35000, array['2 камеры','Цветокор','Тизер'], 'Миша Р.', 'МР', '#f6be62', false),
  ('Ужин по случаю годовщины родителей', 'Другое', 'Декоратор', 'Камерное цветочное оформление семейного ужина.', '2026-11-15', '17:00', 'Монтаж 3 часа', 'Москва', 'Ресторан «Дом культур»', 28000, array['10 гостей','Цветы','Монтаж'], 'Антон В.', 'АВ', '#de8bb7', false),
  ('Свадебная вечеринка без официоза', 'Свадьбы', 'DJ', 'Нужна музыка для живой вечеринки на террасе.', '2026-11-21', '16:00', '6 часов', 'Нижний Новгород', 'Терраса «Маяк»', 50000, array['40 гостей','Оборудование','6 часов'], 'Лера и Дима', 'ЛД', '#77cbb9', false)
on conflict do nothing;
